Added boolean for logger
deuteronomy-works/pyffmpeg pull request #588
Opened 2023-02-23 05:13 UTC by need4swede

## Added boolean to enable / disable logger

### Example

Enable:
`ff = FFmpeg()`

Disable:
`ff = FFmpeg(enable_log=False)`

Quick and easy way to enable 'silent' executions
These changes are not OS dependent, but let me know if should be creating the PR to a different branch

2023-03-06 16:56 UTC, amoh-godwin commented
@need4swede thank you for this PR. I like the idea. You are targeting the right branch for this PR. But certain codes have been deleted which I do not know why.

2023-03-06 17:09 UTC, amoh-godwin requested changes
I actually like the idea. If the codes you deleted should be rewritten, rewrite them I will be checking back very soon to merge the PR. Thank you!

2023-03-06 17:09 UTC, amoh-godwin commented on pyffmpeg/__init__.py
> -            self.logger.info('Conversion Done')
Standard error, in this case, `stderr`, refers to whatever text was printed to the console whiles the application was still running. It is assumed to have been an error message. Standard output is the text that is printed after an application exits, it is the return statement of the application. But now, from what I see, your code is just putting every standard error text into the error variable. This code checks if there was an "output" information, which is the information FFMpeg prints on the output file, if there wasn't then was an error.

2023-03-07 03:00 UTC, need4swede commented
Odd, I don't remember deleting anything...let me look over my files. Perhaps my version didn't have them? I installed it via pip. I'll look things over and will get back to you

2023-03-08 23:58 UTC, need4swede commented
Updated with lines

2023-03-09 21:53 UTC, merged